<b>Problem Statement : From The Given Pokemon.CSV Group Pokemons on the basis of their TYPE1 </b>

In [1]:
import pandas as pd
print('**Grouping of pokemons on the basis of their type 1 using iloc**')
df=pd.read_csv("C:\\Users\\SYED\\Desktop\\Aedifico\\24-10-2019\\CSV Files\\Pokemon.csv")

**Grouping of pokemons on the basis of their type 1**

In [2]:
df.head()

,#,Name,Type1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [5]:
df['Type1'].sort_values()

600      Bug
136      Bug
457      Bug
132      Bug
656      Bug
       ...
172    Water
610    Water
145    Water
574    Water
184    Water
Name: Type1, Length: 800, dtype: object

In [8]:
groupby_type1=df.groupby('Type1') #syntax: varible= dataFrame_name.groupby('Label or column name')

In [12]:
groupby_type1.first() #to acess all groups

,#,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type1,,,,,,,,,,,,
Bug,10,Caterpie,Flying,195,45,30,35,20,20,45,1,False
Dark,197,Umbreon,Flying,525,95,65,110,60,130,65,2,False
Dragon,147,Dratini,Flying,300,41,64,45,50,50,50,1,False
Electric,25,Pikachu,Steel,320,35,55,40,50,50,90,1,False
Fairy,35,Clefairy,Flying,323,70,45,48,60,65,35,1,False
Fighting,56,Mankey,Psychic,305,40,80,35,35,45,70,1,False
Fire,4,Charmander,Flying,309,39,52,43,60,50,65,1,False
Flying,641,TornadusIncarnate Forme,Dragon,580,79,115,70,125,80,111,5,True
Ghost,92,Gastly,Poison,310,30,35,30,100,35,80,1,False
Grass,1,Bulbasaur,Poison,318,45,49,49,65,65,45,1,False
Ground,27,Sandshrew,Rock,300,50,75,85,20,30,40,1,False
Ice,124,Jynx,Psychic,455,65,50,35,115,95,95,1,False
Normal,16,Pidgey,Flying,251,40,45,40,35,35,56,1,False
Poison,23,Ekans,Ground,288,35,60,44,40,54,55,1,False
Psychic,63,Abra,Fairy,310,25,20,15,105,55,90,1,False
Rock,74,Geodude,Ground,300,40,80,100,30,30,20,1,False
Steel,208,Steelix,Ground,510,75,85,200,55,65,30,2,False
Water,7,Squirtle,Fighting,314,44,48,65,50,64,43,1,False

In [13]:
groupby_type1.get_group('Bug') #to acess perticular group in data syntax: groupby_variable.get_group('Group_name')

,#,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
13,10,Caterpie,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,NaN,205,50,20,55,25,25,30,1,False
15,12,Butterfree,Flying,395,60,45,50,90,80,70,1,False
16,13,Weedle,Poison,195,40,35,30,20,20,50,1,False
17,14,Kakuna,Poison,205,45,25,50,25,25,35,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
698,637,Volcarona,Fire,550,85,60,65,135,105,100,5,False
717,649,Genesect,Steel,600,71,120,95,120,95,99,5,False
732,664,Scatterbug,NaN,200,38,35,40,27,25,35,6,False
733,665,Spewpa,NaN,213,45,22,60,27,30,29,6,False
734,666,Vivillon,Flying,411,80,52,50,90,50,89,6,False

In [14]:
groupby_type1.get_group('Water')

,#,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
9,7,Squirtle,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,NaN,630,79,103,120,135,115,78,1,False
59,54,Psyduck,NaN,320,50,52,48,65,50,55,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
724,656,Froakie,NaN,314,41,56,40,62,44,71,6,False
725,657,Frogadier,NaN,405,54,63,52,83,56,97,6,False
726,658,Greninja,Dark,530,72,95,67,103,71,122,6,False
762,692,Clauncher,NaN,330,50,53,62,58,63,44,6,False
763,693,Clawitzer,NaN,500,71,73,88,120,89,59,6,False

In [15]:
groupby_type1.get_group('Dark')

,#,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
212,197,Umbreon,NaN,525,95,65,110,60,130,65,2,False
213,198,Murkrow,Flying,405,60,85,42,85,42,91,2,False
233,215,Sneasel,Ice,430,55,95,55,35,75,115,2,False
246,228,Houndour,Fire,330,45,60,30,80,50,65,2,False
247,229,Houndoom,Fire,500,75,90,50,110,80,95,2,False
248,229,HoundoomMega Houndoom,Fire,600,75,90,90,140,90,115,2,False
284,261,Poochyena,NaN,220,35,55,35,30,30,35,3,False
285,262,Mightyena,NaN,420,70,90,70,60,60,70,3,False
326,302,Sableye,Ghost,380,50,75,75,65,65,50,3,False
327,302,SableyeMega Sableye,Ghost,480,50,85,125,85,115,20,3,False
392,359,Absol,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,NaN,565,65,150,60,115,60,115,3,False
478,430,Honchkrow,Flying,505,100,125,52,105,52,71,4,False
512,461,Weavile,Ice,510,70,120,65,45,85,125,4,False
549,491,Darkrai,NaN,600,70,90,90,135,90,125,4,True
568,509,Purrloin,NaN,281,41,50,37,50,37,66,5,False
569,510,Liepard,NaN,446,64,88,50,88,50,106,5,False
620,559,Scraggy,Fighting,348,50,75,70,35,70,48,5,False
621,560,Scrafty,Fighting,488,65,90,115,45,115,58,5,False
631,570,Zorua,NaN,330,40,65,40,80,40,65,5,False
632,571,Zoroark,NaN,510,60,105,60,120,60,105,5,False
685,624,Pawniard,Steel,340,45,85,70,40,40,60,5,False
686,625,Bisharp,Steel,490,65,125,100,60,70,70,5,False
690,629,Vullaby,Flying,370,70,55,75,45,65,60,5,False
691,630,Mandibuzz,Flying,510,110,65,105,55,95,80,5,False
694,633,Deino,Dragon,300,52,65,50,45,50,38,5,False
695,634,Zweilous,Dragon,420,72,85,70,65,70,58,5,False
696,635,Hydreigon,Dragon,600,92,105,90,125,90,98,5,False
756,686,Inkay,Psychic,288,53,54,53,37,46,45,6,False
757,687,Malamar,Psychic,482,86,92,88,68,75,73,6,False
793,717,Yveltal,Flying,680,126,131,95,131,98,99,6,True